version: '3.7'
services:
  bot:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - "postgres_data:${POSTGRES_DATA}"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
volumes:
  postgres_data: